//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MineWatcher.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MineWatcher.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App is designed to help you watch over your bitcoin miner on a PolMine server. Other extra servers will be added in a future (slush pool etc.)..
        /// </summary>
        public static string AboutAppDesc {
            get {
                return ResourceManager.GetString("AboutAppDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application:.
        /// </summary>
        public static string AboutAppTitle {
            get {
                return ResourceManager.GetString("AboutAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student of the PJWSTK in Warsaw, Android and Windows Phone developer..
        /// </summary>
        public static string AboutMeDesc {
            get {
                return ResourceManager.GetString("AboutMeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Michał Tajchert.
        /// </summary>
        public static string AboutMeName {
            get {
                return ResourceManager.GetString("AboutMeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string AboutMeTitle {
            get {
                return ResourceManager.GetString("AboutMeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More about me.
        /// </summary>
        public static string AboutMoreMe {
            get {
                return ResourceManager.GetString("AboutMoreMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate this app.
        /// </summary>
        public static string AboutRateThisApp {
            get {
                return ResourceManager.GetString("AboutRateThisApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance:.
        /// </summary>
        public static string BalanceText {
            get {
                return ResourceManager.GetString("BalanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralTitle {
            get {
                return ResourceManager.GetString("GeneralTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last online:.
        /// </summary>
        public static string LastOnline {
            get {
                return ResourceManager.GetString("LastOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payout:.
        /// </summary>
        public static string PayoutText {
            get {
                return ResourceManager.GetString("PayoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can be found at your account at PolMine.pl.
        /// </summary>
        public static string SettingsDesc {
            get {
                return ResourceManager.GetString("SettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SettingsSaveButton {
            get {
                return ResourceManager.GetString("SettingsSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes to mark miner as offline:.
        /// </summary>
        public static string SettingsTimeDesc {
            get {
                return ResourceManager.GetString("SettingsTimeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your API Token.
        /// </summary>
        public static string SettingsTokenInput {
            get {
                return ResourceManager.GetString("SettingsTokenInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shares: .
        /// </summary>
        public static string Shares {
            get {
                return ResourceManager.GetString("Shares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum:.
        /// </summary>
        public static string SpeedSum {
            get {
                return ResourceManager.GetString("SpeedSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stale: .
        /// </summary>
        public static string Stale {
            get {
                return ResourceManager.GetString("Stale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MineWatcher.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
